var caracteristicas = [
    "En 2 lotes de 75 mts ancho x 240 mts largo c/u. (total: 150 frente x 240 mts largo). 3,6 Hectáreas.",
    "Rejas reforzadas en todas las puertas y ventanas.",
    "EXCELENTE Construcción y Terminaciones. De PRIMERA calidad.",
    "Techos con aislantes de fibra de vidrio y térmicos, dependiendo del lugar.",
    "A SOLO 300 mts del ASFALTO (Estancia Chica) con entrada mejorada de piedra, y 1.000 mts de Estación Abasto.",
    "Aproximadamente 750 mts lineales de alambrado olímpico perimetral de excelente calidad, con mallado de calibre 12. Excelente calidad e instalación.",
    "340 mts2 cubiertos. 95 mts2 semicubiertos.",
    "2 Portones corredizos con control remoto, portero visor, y paredón iluminado por dentro y por fuera. Tercer portón corredizo en Galpón.",
    "Pintada íntegramente por dentro y por fuera.",
    "Electricidad y sistema eléctrico de Primera Calidad. Con disyuntores y térmicas independientes para cada sector de la casa.",
    "3 lineas de energía eléctrica.",
    "GARAJE/GALPON de 14,70 mts de largo por 6,50 mts de ancho, con techo aislante calor/frio/ruido. Apto también para salón de juegos o similar. Con equipo de aire frio calor de 6.000 frigorías.",
    "6 equipos de aire FRIO/CALOR BGH nuevos. Son 3 de 3.000 frigorias, y 2 de 6.000 frigorias.",
    "Patio trasero / Quincho, con parrilla, y 2 termotanques (eléctrico y a gas, de alta recuperación ).",
    "Tanque de gas envasado, tamaño mediano.",
    "CONTAINER grande. Tamaño Boing de 40 pies. Acondicionado como galpon, con división interna. Enb estado impecable, techado.",
    "Bomba de Agua sumergible a 60 mts aproximadamente, marca Motorarg. (Agua Semi-mineral). Presurizadora.",
    "2 Tanques de Agua de 1.100 litros cada uno de ellos. Total: 2.200 lts.",
    "Sistema de Alarma con sensores en toda la casa. Circuito cerrado de Cámaras. (falta instalación de las cámaras).",
    "Excelente Iluminación perimetral, con postes de alumbrado alrededor de la casa.",
]
